remote_theme: mmistakes/minimal-mistakes
title: Galaxy NGC 891
include: ["_pages"]


author:
  name: Elizabeth Oommen
  avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/220px-Grosser_Panda.JPG"
  bio: Animals for life
